apiVersion: v1
kind: Service
metadata:
  name: {{ include "faikChallenge.consumerAppName" .}}
  labels:
    {{- include "faikChallenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.consumer.service.type }}
  ports:
    - port: {{ .Values.consumer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "faikChallenge.selectorLabels" . | nindent 4 }}
    {{- include "faikChallenge.consumerSelectorLabels" . | nindent 4 }}