# Default values for faikChallenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
producer:
  image:
    repository: faikyildirim/demoproducer
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v4-arm64" #for arm64 arch
  quename: "CustomQue"
  service:
    type: ClusterIP
    port: 8080

consumer:
  image:
    repository: faikyildirim/democonsumer
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v2-arm64" #for arm64 arch
  quename: "CustomQue"
  service:
    type: ClusterIP
    port: 8080




nameOverride: ""
fullnameOverride: ""
 



 
 
 